[source.crates-io]
replace-with = "ustc-sparse"

[source.rsproxy-sparse]
registry = "sparse+https://rsproxy.cn/index/"

[source.ustc-sparse]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[http]
check-revoke = false

[net]
git-fetch-with-cli = true
